from __future__ import annotations

from typing import Any

from app.adapters.ai_provider import ai_provider
from app.listing_limits import enforce_amazon_copy


def _bullets(name: str, features: list[str]) -> list[str]:
    seeds = features[:5] or [
        f"{name} uses on-device AI for safer kids interaction",
        "Simple one-tap stories, songs, and Q&A",
        "Parent-friendly volume and session controls",
        "Durable toy-grade housing for daily play",
        "Ready for Amazon, TikTok Shop, and Shopify listings",
    ]
    while len(seeds) < 5:
        seeds.append(f"{name} is designed for everyday family use")
    return seeds[:5]


class ContentFactory:
    """渠道文案工厂。字段映射参考 open-listing-studio，实现留在 JoyOPC。"""

    source = "https://github.com/clawnify/open-listing-studio"

    def generate(self, product: dict[str, Any], channel: str = "all") -> dict[str, Any]:
        name = str(product.get("name") or "AI Toy")
        sku = str(product.get("sku") or "")
        features = [str(item) for item in (product.get("features") or []) if str(item).strip()]
        bullets = _bullets(name, features)
        local = {
            "sku": sku,
            "product_name": name,
            "amazon": {
                "title": f"{name} AI Companion Toy for Kids",
                "bullets": bullets,
                "description": f"{name} is an AI toy listing generated by JoyOPC Content Factory. " + " ".join(bullets),
                "search_terms": "ai toy, kids companion, talking plush, educational toy",
            },
            "shopify": {
                "seo_title": name,
                "description_html": f"<p>{name}</p><ul>" + "".join(f"<li>{b}</li>" for b in bullets) + "</ul>",
                "tags": ["ai-toy", "kids", "companion"],
            },
            "tiktok_shop": {
                "short_title": name[:60],
                "selling_points": bullets[:3],
                "video_script": f"Hook: {name} talks back. Problem: kids want a playmate. Demo: one tap story. CTA: tap to shop.",
            },
        }
        generated = ai_provider.complete_json(
            "Generate marketplace listings for Amazon, Shopify and TikTok Shop. Keep claims conservative. Keys: amazon, shopify, tiktok_shop.",
            local,
        )
        listings = {
            "amazon": enforce_amazon_copy(generated.get("amazon") or local["amazon"]),
            "shopify": generated.get("shopify") or local["shopify"],
            "tiktok_shop": generated.get("tiktok_shop") or local["tiktok_shop"],
        }
        wanted = channel.strip().lower().replace(" ", "_")
        if wanted in listings:
            listings = {wanted: listings[wanted]}
        return {
            "provider": generated.get("provider") or ai_provider.status()["active_provider"],
            "inspired_by": self.source,
            "listings": listings,
        }


content_factory = ContentFactory()
